// <auto-generated/>
namespace ReSharperPlugin.Verify
{
  using System;
  using JetBrains.Application.I18n;
  using JetBrains.DataFlow;
  using JetBrains.Diagnostics;
  using JetBrains.Lifetimes;
  using JetBrains.Util;
  using JetBrains.Util.Logging;
  using JetBrains.Application.I18n.Plurals;
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public static class Resources
  {
    private static readonly ILogger ourLog = Logger.GetLogger("ReSharperPlugin.Verify.Resources");

    static Resources()
    {
      CultureContextComponent.Instance.Change.Advise(Lifetime.Eternal, args =>
      {
          var instance = args.HasNew ? args.New : null;
          if (instance != null)
          {
            ourResourceManager = new Lazy<JetResourceManager>(
              () =>
              {
                return instance
                  .CreateResourceManager("ReSharperPlugin.Verify.Resources", typeof(Resources).Assembly);
              });
          }
          else
          {
            ourResourceManager = null;
          };
      });
    }
    
    private static Lazy<JetResourceManager> ourResourceManager = null;
    
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static JetResourceManager ResourceManager
    {
      get
      {
        var resourceManager = ourResourceManager;
        if (resourceManager == null)
        {
          return ErrorJetResourceManager.Instance;
        }
        return resourceManager.Value;
      }
    }

    public static string Choice(string format, params object[] args)
    {
        var formatter = ResourceManager.ChoiceFormatter;
        if (formatter == null) return "???";
        return string.Format(formatter, format, args);
    }

    public static string VerifyAcceptActionText => ResourceManager.GetString("VerifyAcceptActionText");
    public static string VerifyCompareActionText => ResourceManager.GetString("VerifyCompareActionText");
    public static string VerifyOpenActionText => ResourceManager.GetString("VerifyOpenActionText");
    public static string VerifyRerunActionText => ResourceManager.GetString("VerifyRerunActionText");
  }
}